import time

class HW_FlashDecoding_ReductionFuser:
    def __init__(self, num_blocks=256, dim=4096):
        self.num_blocks = num_blocks
        self.dim = dim
        self.bytes_per_state = self.dim * 2 # FP16 partial states
        
    def simulate_baseline_reduction(self):
        # Software Flash-Decoding partial reduction overhead
        # Read all partial states from SRAM, reduce, write final state
        bandwidth = 100 * 1024**3 # 100 GB/s internal SRAM bandwidth
        bytes_to_read = self.num_blocks * self.bytes_per_state
        latency = bytes_to_read / bandwidth
        return latency

    def simulate_hw_fused_reduction(self):
        # Hardware inline reduction tree
        # Reduces states on the fly as they are generated by SMs, no intermediate SRAM writes/reads
        # The only latency is the pipeline depth of the adder tree
        tree_depth_cycles = 8 # log2(256)
        clock_freq = 1.0 * 10**9 # 1 GHz
        latency = tree_depth_cycles / clock_freq
        return latency

def run_sim():
    print("Running Hardware Flash-Decoding Reduction Fuser (HW-FDRF) Simulation...")
    sim = HW_FlashDecoding_ReductionFuser()
    
    base_latency = sim.simulate_baseline_reduction()
    hw_latency = sim.simulate_hw_fused_reduction()
    
    speedup = base_latency / hw_latency if hw_latency > 0 else float('inf')
    
    print(f"Baseline Reduction Latency: {base_latency * 1000:.4f} ms")
    print(f"HW-FDRF Latency: {hw_latency * 1000:.4f} ms")
    print(f"Speedup: {speedup:.2f}x")

if __name__ == '__main__':
    run_sim()
