import random

def simulate_speculative_decoding(num_tokens=100, gamma=4, draft_hit_rate=0.7):
    # Standard decoding: load main model weights N times from DRAM
    # Speculative decoding: 
    #   load draft model weights N times (draft model is 1/10th size)
    #   load main model weights N / (gamma * hit_rate + 1) times (batched verification)
    
    # Assume Main model is 14GB, Draft model is 1.4GB
    main_model_size = 14.0
    draft_model_size = 1.4
    
    # Standard decoding memory bandwidth usage
    std_bw_gb = num_tokens * main_model_size
    
    # Speculative decoding simulation
    accepted_tokens = 0
    verification_steps = 0
    draft_bw_gb = 0
    
    while accepted_tokens < num_tokens:
        # Draft model generates 'gamma' tokens
        draft_bw_gb += draft_model_size * gamma
        
        # Main model verifies 'gamma' tokens in ONE forward pass (batching)
        # Memory loaded ONCE for verification
        verification_steps += 1
        
        # Simulate acceptance
        accepted_this_step = 0
        for _ in range(gamma):
            if random.random() < draft_hit_rate:
                accepted_this_step += 1
            else:
                break # reject this and all subsequent
        
        # +1 for the token generated by the main model during verification
        accepted_tokens += accepted_this_step + 1

    spec_main_bw_gb = verification_steps * main_model_size
    total_spec_bw_gb = draft_bw_gb + spec_main_bw_gb
    
    return std_bw_gb, total_spec_bw_gb, num_tokens / verification_steps

if __name__ == "__main__":
    print("Speculative Decoding Memory Bandwidth Analysis")
    
    for hit_rate in [0.5, 0.7, 0.9]:
        std_bw, spec_bw, speedup = simulate_speculative_decoding(num_tokens=1000, gamma=5, draft_hit_rate=hit_rate)
        
        print(f"\\nDraft Hit Rate: {hit_rate*100:.0f}%")
        print(f"  Standard Decoding Bandwidth: {std_bw:.2f} GB")
        print(f"  Speculative Decoding Bandwidth: {spec_bw:.2f} GB")
        print(f"  Bandwidth Reduction: {(1 - spec_bw/std_bw)*100:.2f}%")
        print(f"  Effective Token Speedup: {speedup:.2f}x")
